In [1]:
import numpy as np
from scipy.sparse.linalg import aslinearoperator
from scipy.stats import ortho_group

import tracelogdetdiag as tld
from tracelogdetdiag.logdet import logdet_via_cholesky
from tracelogdetdiag.diag import naive_diag, explicit_diag_probe
from tracelogdetdiag.diaginv import naive_diaginv, explicit_diaginv_probe
from tracelogdetdiag.trace import hutch_plus_plus_trace, hutch_plus_plus_epsilon_delta_trace, hutchinson_trace, hutchinson_epsilon_delta_trace
from tracelogdetdiag.logdet import logdet_stochastic_chebyshev_approx, logdet_stochastic_chebyshev_epsilon_delta_approx

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


# NumPy

## Test matrix

In [2]:
d = 100

np.random.seed(0)
basis = ortho_group.rvs(d)
eigvals = np.random.uniform(low=5.0, high=10.0, size=d)
B = basis @ np.diag(eigvals) @ basis.T
true_logdet = logdet_via_cholesky(B)
true_diag = np.diag(B)
true_diaginv = np.diag(np.linalg.inv(B))
true_trace = np.trace(B)
B_explicit = B.copy()
B = aslinearoperator(B)


## Diagonal

In [3]:
explicit_diag_probe(B) - true_diag

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
naive_diag(B) - true_diag

array([ 8.43094693e-03, -1.25223562e-02, -4.73592191e-02,  4.35608115e-02,
       -4.45923191e-02, -1.76802045e-02,  8.02166144e-02, -7.17044621e-02,
       -4.21627017e-02, -9.31753573e-04,  1.83723302e-02, -6.90830999e-02,
       -1.32597846e-02,  1.03354299e-02, -5.49389940e-02,  1.72362663e-02,
        2.70525458e-02, -1.04746023e-01,  1.57269787e-02,  8.79181919e-02,
       -4.26599842e-02,  4.13553995e-03, -1.26126246e-01, -2.41501291e-02,
       -2.47651350e-02,  9.51324860e-04, -8.40951993e-02, -2.65819505e-02,
       -9.03133357e-02,  4.57411090e-02, -3.39469692e-02, -6.09885149e-03,
       -9.65331589e-03, -2.00244177e-03, -5.89663073e-02, -4.65574051e-02,
        8.43231635e-02,  6.55250474e-02,  2.09011699e-02,  7.29635050e-02,
        5.66430327e-02, -8.60005617e-03, -3.99461784e-02,  1.99937812e-02,
       -4.50441399e-02,  2.24287570e-02,  5.13986603e-03, -7.65043456e-02,
        7.32402662e-03, -1.42496096e-02, -3.73819709e-02,  3.98226237e-02,
        1.14007917e-01,  

## Diagonal inverse

In [5]:
explicit_diaginv_probe(B_explicit) - true_diaginv

array([ 5.55111512e-17, -2.77555756e-17,  2.77555756e-17,  8.32667268e-17,
       -5.55111512e-17,  0.00000000e+00,  0.00000000e+00, -2.77555756e-17,
        0.00000000e+00, -1.11022302e-16,  0.00000000e+00, -2.77555756e-17,
        2.77555756e-17,  0.00000000e+00, -2.77555756e-17,  2.77555756e-17,
        5.55111512e-17,  2.77555756e-17,  8.32667268e-17,  0.00000000e+00,
        0.00000000e+00,  5.55111512e-17, -5.55111512e-17, -8.32667268e-17,
        0.00000000e+00,  8.32667268e-17,  0.00000000e+00,  2.77555756e-17,
        0.00000000e+00,  0.00000000e+00,  2.77555756e-17, -2.77555756e-17,
        2.77555756e-17,  0.00000000e+00, -2.77555756e-17, -2.77555756e-17,
        2.77555756e-17,  5.55111512e-17,  5.55111512e-17,  5.55111512e-17,
       -5.55111512e-17, -5.55111512e-17,  0.00000000e+00,  0.00000000e+00,
        2.77555756e-17,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        5.55111512e-17,  2.77555756e-17,  2.77555756e-17,  5.55111512e-17,
        5.55111512e-17,  

In [6]:
naive_diaginv(B_explicit, sample_size=20) - true_diaginv

array([ 0.00866717, -0.00844657,  0.00442414,  0.00313819, -0.00283634,
       -0.00176077,  0.00401723,  0.00384309, -0.00496591, -0.01552035,
       -0.00553858, -0.00961716, -0.00012473, -0.00285512, -0.00305861,
        0.00351386, -0.00036131, -0.00267292, -0.00800138, -0.00193513,
        0.01082293,  0.00573904, -0.00346373,  0.01533509, -0.00999309,
        0.00102349,  0.01081379, -0.00510388, -0.00092665, -0.00024388,
        0.00253949, -0.00274681, -0.00741256,  0.00560801,  0.00291684,
        0.00568469,  0.00109555,  0.00053872,  0.0056227 ,  0.00200898,
        0.00105971,  0.00386607,  0.00250004,  0.00390176,  0.00129357,
       -0.00281133,  0.00962792, -0.00189067, -0.01216109, -0.00268834,
       -0.00179991, -0.00943469,  0.00025651,  0.00150102,  0.00250192,
       -0.00459391, -0.01145364,  0.00033498, -0.0101512 ,  0.00330808,
        0.00934712, -0.00735016, -0.00453767,  0.00479931,  0.01029238,
        0.0024762 ,  0.0069954 , -0.00239568,  0.01256156,  0.00

## Trace

In [7]:
true_trace

751.9064661900678

In [8]:
hutch_plus_plus_epsilon_delta_trace(B, epsilon=0.01, delta=0.01)

759.4477368560804

In [9]:
hutch_plus_plus_trace(B, sample_size=3*1000)

751.9064661900678

In [10]:
hutchinson_epsilon_delta_trace(B, epsilon=0.1, delta=0.1)

751.5140270206803

In [11]:
hutchinson_trace(B, sample_size=2000)

752.5617300863227

## Logdet

In [12]:
true_logdet

199.82635170788498

In [13]:
logdet_stochastic_chebyshev_approx(B, sample_size=300)

199.9076408060301

In [14]:
logdet_stochastic_chebyshev_epsilon_delta_approx(B)

199.85521538788862

# CuPy

## Test matrix

In [16]:
import cupy as cp
from cupyx.scipy.sparse.linalg import LinearOperator as CuPyLinearOperator
from cupyx.scipy.sparse.linalg import aslinearoperator as cupyaslinearoperator

In [18]:
d = 1000

cp.random.seed(0)
basis = ortho_group.rvs(d)
eigvals = np.random.uniform(low=5.0, high=10.0, size=d)
B_numpy = basis @ np.diag(eigvals) @ basis.T
basis = cp.asarray(basis)
B = basis @ cp.diag(cp.asarray(eigvals)) @ basis.T
true_logdet = logdet_via_cholesky(B_numpy)
true_diag = np.diag(B_numpy)
true_diaginv = np.diag(np.linalg.inv(B_numpy))
true_trace = np.trace(B_numpy)
B_explicit = B_numpy.copy()
B = cupyaslinearoperator(B)

## Diagonal

In [20]:
cp.linalg.norm(explicit_diag_probe(B) - cp.asarray(true_diag))

array(6.24383744e-14)

In [21]:
cp.linalg.norm(naive_diag(B) - cp.asarray(true_diag))/len(true_diag)

array(0.00144637)

## Diagonal inverse

## Trace

## Logdet